print out (item pair, count) for counts > 2
mzwong/uvahelpr pull request #23
Opened 2016-12-06 21:01 UTC by will-gerard

2016-12-06 21:18 UTC, ag4ml requested changes

2016-12-06 21:18 UTC, ag4ml commented on data/mapreduce.py
> +click_counts = click_pairs.map(lambda pair: (pair[0], len(pair[1])))
Should be the count of distinct users. Maybe change it to len(set(pair[1]))

2016-12-07 03:04 UTC, ag4ml approved these changes

2016-12-07 19:43 UTC, mzwong approved these changes

2016-12-07 19:46 UTC, merged